// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfpIoDWnhk09OCh2B0c8_URsSdAott2U',
    appId: '1:849117762158:android:c19010673e73696c3b4c7f',
    messagingSenderId: '849117762158',
    projectId: 'enitproject',
    storageBucket: 'enitproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-7tf6HpMgtirf_YYKXaYQeSyXXKPsf6w',
    appId: '1:849117762158:ios:c813b499b40a63f43b4c7f',
    messagingSenderId: '849117762158',
    projectId: 'enitproject',
    storageBucket: 'enitproject.appspot.com',
    androidClientId: '849117762158-0u27n38r8k4aolqir5fi8lja34m0l5j3.apps.googleusercontent.com',
    iosClientId: '849117762158-o8akorq0566nfuj1n9mfbl0jpnphop4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.enitproject',
  );
}
